name: Bump version
on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: '0'
        
    - name: Colculate and push tag for development
      id: tag
      uses: Magikon/mtag@development
      env:
        INITIAL_VERSION: 0.0.0
        TAG_CONTEXT: repo
        RELEASE_BRANCHES: development
        PRERELEASE_SUFFIX: dev
        MAJOR: "BREAKING*CHANGE|*#major*"
        MINOR: "*feat*|*#minor*"
        PATCH: "*fix*|*chore*|*docs*|*update*|*patch*"
        FORCE: true
        OVERWRITE: true
        NOMERGES: true
        
    - name: Echo variables
      env:
        NEW_TAG: ${{ steps.tag.outputs.new_tag }}
        SEL_TAG: ${{ steps.tag.outputs.tag }}
        PART: ${{ steps.tag.outputs.part }}
      run: |
        echo "New Tag"
        echo $NEW_TAG
        echo "Tag"
        echo $SEL_TAG
        echo "Part"
        echo $PART
